---
- name: etcd service file
  shell: |
    cat <<EOF | sudo tee /etc/systemd/system/etcd.service
    [Unit]
    Description={{ description }}
    Documentation={{ documentation }}

    [Service]
    Type={{ type }}
    User={{ etcd_user }}
    ExecStart={{ etcd_bin }}/etcd \\
      --name $HOSTNAME \\
      --enable-v2=true \\
      --data-dir={{ etcd_home }} \\
      --initial-advertise-peer-urls http://$(ip addr show eth1 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1):{{ etcd_raft_port }} \\
      --listen-peer-urls http://$(ip addr show eth1 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1):{{ etcd_raft_port }} \\
      --listen-client-urls http://$(ip addr show eth1 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1):{{ etcd_connection_port }},http://127.0.0.1:{{ etcd_connection_port }} \\
      --advertise-client-urls http://$(ip addr show eth1 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1):{{ etcd_connection_port }} \\
      --initial-cluster-token etcd-cluster-0 \\
      --initial-cluster etcd0=http://{{ etcd0_ip }}:{{ etcd_raft_port }},etcd1=http://{{ etcd1_ip }}:{{ etcd_raft_port }},etcd2=http://{{ etcd2_ip }}:{{ etcd_raft_port }} \\
      --initial-cluster-state new \

    [Install]
    WantedBy=multi-user.target
    EOF
  args:
      executable: /bin/bash

- name: systemd to reread configs
  systemd:
    daemon_reload: yes
