---
- name: upgrade all packages
  yum:
    name: "*"
    state: latest

- name: install required os packages
  yum:
    name: "{{ os_packages }}"
    state: present

- name: start service firewalld
  systemd:
    state: started
    name: firewalld

- name: enable service firewalld
  systemd:
    name: firewalld
    enabled: yes
    masked: no

- name: add etcd hosts to hosts file
  shell: |
    tee -a /etc/hosts<<EOF
    {{ etcd0_ip }} {{ etcd0_name }} {{ etcd0_name }}
    {{ etcd1_ip }} {{ etcd1_name }} {{ etcd1_name }}
    {{ etcd2_ip }} {{ etcd2_name }} {{ etcd2_name }}
    EOF
  args:
    executable: /bin/bash
